[package]
name = "rust_service"
version = "0.1.0"
edition = "2021"

[dependencies]
winreg = "0.10"
tokio = { version = "1", features = ["full"] }
winapi = { version = "0.3", features = ["processthreadsapi", "winnt", "securitybaseapi"] }
